dependencies:
  auto_route: ^7.8.3
  cupertino_icons: ^1.0.8
  expandable: ^5.0.1
  fetch_client: ^1.0.2
  firebase_analytics: ^10.7.0
  firebase_core: ^2.22.0
  firebase_crashlytics: ^3.4.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_highlighter: ^0.1.1
  flutter_markdown_selectionarea: ^0.6.17+1
  flutter_spinkit: ^5.2.0
  google_fonts: ^6.1.0
  highlight: ^0.7.0
  http: ^1.1.0
  hydrated_bloc: ^9.1.2
  image: ^4.0.17
  intl: ^0.18.1
  json_annotation: ^4.8.1
  markdown: ^7.1.1
  open_file_plus: ^3.4.1
  url_strategy: ^0.2.0
  uuid: ^3.0.4
dependency_overrides:
  image_picker:
    git:
      path: packages/image_picker/image_picker
      url: https://gitee.com/openharmony-sig/flutter_packages.git
  package_info_plus:
    git:
      path: packages/package_info_plus/package_info_plus
      url: https://gitee.com/openharmony-sig/flutter_plus_plugins.git
  path_provider:
    git:
      path: packages/path_provider/path_provider
      url: https://gitee.com/openharmony-sig/flutter_packages.git
  permission_handler:
    git:
      path: permission_handler
      url: https://gitee.com/openharmony-sig/flutter_permission_handler.git
  url_launcher:
    git:
      path: packages/url_launcher/url_launcher
      url: https://gitee.com/openharmony-sig/flutter_packages.git
description: Demux app.
dev_dependencies:
  auto_route_generator: ^7.3.1
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
environment:
  sdk: '>3.0.0 <=3.4.0'
flutter:
  assets:
  - assets/app_icon.png
  uses-material-design: true
name: demux_app
publish_to: none
version: 2.0.0+1200001
